package com.dnikitin.entity.embeddedcomponent;

import com.dnikitin.entity.converter.BirthdayConverter;
import com.dnikitin.entity.user.Birthday;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Entity
@Table(name = "users1")
public class User1 {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    /*
    * auto (defines by db type and dialect, for postgres auto = sequence)
    *
    * identity - autogenerated key inside DB
    *
    * sequence(counter with custom properties - need to create sequence inside sql)
    * @GeneratedValue(generator = "user_gen", strategy = GenerationType.SEQUENCE)
    * @SeqienceGenerator(name = "user_gen", sequenceName = "name_from_db", allocationSize = 50)
    *
    * table - if db does not support autogenerated keys (@TableGenerator)
     */
    long id;

    @Column(unique = true)
    private String username;

    //to override names of the fields inside PersonalInfo
    @Embedded
    @AttributeOverride(name = "name", column = @Column(name = "firstname"))
    @AttributeOverride(name = "surname", column = @Column(name = "lastname"))
    @AttributeOverride(name = "phoneNumber", column = @Column(name = "phone_number"))
    private PersonalInfo personalInfo;

    @Column(name = "birth_date")
    @Convert(converter = BirthdayConverter.class)
    //this annotation allows to not save and upload this field to DB
    @Transient
    private Birthday birthDate;
}
